name: Package Application with Pyinstaller

on:
  release:
    types: [published]

jobs:
  build_windows:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Package Application
      uses: JackMcKew/pyinstaller-action-windows@main
      with:
        path: .

    - uses: actions/upload-artifact@v2
      with:
        name: ProgressSheetUpdater.exe
        path: src/dist/windows